### ISSUE TITLE
Any advantages to upgrading to the reactive ws in Spring 5?

### ISSUE THREAD

**Issue by mycroft11** [ralscha/wamp2spring#1]

**Comment by ralscha** [comment]
I see: https://docs.spring.io/spring/docs/5.0.2.RELEASE/spring-framework-reference/web-reactive.html#webflux-websocket

They added reactive WebSocket support. I was not aware. 
One advantage is that this also runs on Netty. 

Need to look into that. Would be nice to support this in wamp2spring too. 

Thanks for the info.

**Comment by ralscha** [comment]
I wrote a simple Spring Reactive integration:     
https://github.com/ralscha/wamp2spring/tree/master/wamp2spring-reactive

That's not a re-implementation of the whole wamp2spring system. Just an implementation of org.springframework.web.reactive.socket.WebSocketHandler that feeds the messages into the wamp2spring message channels. 

This allows you to run wamp2spring on the Spring reactive stack. 

You find an example here: 
https://github.com/ralscha/wamp2spring-demo/tree/master/reactive
