### ISSUE TITLE
Subscription options

### ISSUE THREAD

**Issue by piotrblasiak** [ralscha/wamp2spring#9]
Hi,

Is there any way to send along options with a subscription? I can only see a way of getting subscription to topics with no options.

**Comment by ralscha** [comment]
There should be a way. The wamp specification for subscribe looks like this

```
[SUBSCRIBE, Request|id, Options|dict, Topic|uri]
```
https://wamp-proto.org/_static/gen/wamp_latest.html#subscribe


The subscribe method in Autobahn-js takes options as a third argument
```
Session.prototype.subscribe = function (topic, handler, options) {
```
https://github.com/crossbario/autobahn-js/blob/master/packages/autobahn/lib/session.js#L1335

**Comment by piotrblasiak** [comment]
Exactly - but I can't see anywhere in wamp2spring (SubscriptionDetail or similar) where I could fetch these options?

**Comment by ralscha** [comment]
I see. You are right. The library parses the options object and checks for a `match` field, but after that it throws it away.
https://github.com/ralscha/wamp2spring/blob/master/wamp2spring-core/src/main/java/ch/rasc/wamp2spring/message/SubscribeMessage.java#L64-L88

I think this should not be too complicated to pass the options object to the SubscribeMessage object and from there to the SubscriptionDetail.
